// astertower
// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

// AstroListerExpansion allows custom methods to be added to
// AstroLister.
type AstroListerExpansion interface{}

// AstroNamespaceListerExpansion allows custom methods to be added to
// AstroNamespaceLister.
type AstroNamespaceListerExpansion interface{}
