// astertower
// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	time "time"

	apisv1alpha1 "github.com/kasterism/astertower/pkg/apis/v1alpha1"
	astertower "github.com/kasterism/astertower/pkg/clients/clientset/astertower"
	internalinterfaces "github.com/kasterism/astertower/pkg/clients/informer/externalversions/internalinterfaces"
	v1alpha1 "github.com/kasterism/astertower/pkg/clients/lister/apis/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// AstroInformer provides access to a shared informer and lister for
// Astros.
type AstroInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha1.AstroLister
}

type astroInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewAstroInformer constructs a new informer for Astro type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewAstroInformer(client astertower.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredAstroInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredAstroInformer constructs a new informer for Astro type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredAstroInformer(client astertower.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.AstertowerV1alpha1().Astros(namespace).List(context.TODO(), options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.AstertowerV1alpha1().Astros(namespace).Watch(context.TODO(), options)
			},
		},
		&apisv1alpha1.Astro{},
		resyncPeriod,
		indexers,
	)
}

func (f *astroInformer) defaultInformer(client astertower.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredAstroInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *astroInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&apisv1alpha1.Astro{}, f.defaultInformer)
}

func (f *astroInformer) Lister() v1alpha1.AstroLister {
	return v1alpha1.NewAstroLister(f.Informer().GetIndexer())
}
