// astertower
// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	internalinterfaces "github.com/kasterism/astertower/pkg/clients/informer/externalversions/internalinterfaces"
)

// Interface provides access to all the informers in this group version.
type Interface interface {
	// Astros returns a AstroInformer.
	Astros() AstroInformer
}

type version struct {
	factory          internalinterfaces.SharedInformerFactory
	namespace        string
	tweakListOptions internalinterfaces.TweakListOptionsFunc
}

// New returns a new Interface.
func New(f internalinterfaces.SharedInformerFactory, namespace string, tweakListOptions internalinterfaces.TweakListOptionsFunc) Interface {
	return &version{factory: f, namespace: namespace, tweakListOptions: tweakListOptions}
}

// Astros returns a AstroInformer.
func (v *version) Astros() AstroInformer {
	return &astroInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}
