// astertower
// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	"time"

	v1alpha1 "github.com/kasterism/astertower/pkg/apis/v1alpha1"
	scheme "github.com/kasterism/astertower/pkg/clients/clientset/astertower/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// AstrosGetter has a method to return a AstroInterface.
// A group's client should implement this interface.
type AstrosGetter interface {
	Astros(namespace string) AstroInterface
}

// AstroInterface has methods to work with Astro resources.
type AstroInterface interface {
	Create(ctx context.Context, astro *v1alpha1.Astro, opts v1.CreateOptions) (*v1alpha1.Astro, error)
	Update(ctx context.Context, astro *v1alpha1.Astro, opts v1.UpdateOptions) (*v1alpha1.Astro, error)
	UpdateStatus(ctx context.Context, astro *v1alpha1.Astro, opts v1.UpdateOptions) (*v1alpha1.Astro, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.Astro, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.AstroList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.Astro, err error)
	AstroExpansion
}

// astros implements AstroInterface
type astros struct {
	client rest.Interface
	ns     string
}

// newAstros returns a Astros
func newAstros(c *AstertowerV1alpha1Client, namespace string) *astros {
	return &astros{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the astro, and returns the corresponding astro object, and an error if there is any.
func (c *astros) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.Astro, err error) {
	result = &v1alpha1.Astro{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("astros").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of Astros that match those selectors.
func (c *astros) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.AstroList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.AstroList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("astros").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested astros.
func (c *astros) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("astros").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a astro and creates it.  Returns the server's representation of the astro, and an error, if there is any.
func (c *astros) Create(ctx context.Context, astro *v1alpha1.Astro, opts v1.CreateOptions) (result *v1alpha1.Astro, err error) {
	result = &v1alpha1.Astro{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("astros").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(astro).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a astro and updates it. Returns the server's representation of the astro, and an error, if there is any.
func (c *astros) Update(ctx context.Context, astro *v1alpha1.Astro, opts v1.UpdateOptions) (result *v1alpha1.Astro, err error) {
	result = &v1alpha1.Astro{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("astros").
		Name(astro.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(astro).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *astros) UpdateStatus(ctx context.Context, astro *v1alpha1.Astro, opts v1.UpdateOptions) (result *v1alpha1.Astro, err error) {
	result = &v1alpha1.Astro{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("astros").
		Name(astro.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(astro).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the astro and deletes it. Returns an error if one occurs.
func (c *astros) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("astros").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *astros) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("astros").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched astro.
func (c *astros) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.Astro, err error) {
	result = &v1alpha1.Astro{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("astros").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
